menu:
  #Archives: /archives
  主页: /
  所有文章: /archives
  #我是: /aboutme
rss: /atom.xml
description: 
social:
  github: "https://github.com/rockerhx"
  weibo: "http://weibo.com/ganmaojijie"
  google: "https://plus.google.com/u/0/117148620342014164803"
  facebook: ""
  twitter: "https://twitter.com/rockerhx"

page_comment: false
logo: /images/avatar.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: rockerhx

baidu_tongji: f1811f144f64379f918cf1ef7bf3f3cb
favicon: /images/avatar-small.jpg

