menu:
  所有文章: /archives
  # 我是: /aboutme
# rss: /atom.xml
description: 
social:
  github: "https://github.com/rockerhx"
  weibo: "http://weibo.com/ganmaojijie"
  google: "https://plus.google.com/u/0/117148620342014164803"
  facebook: ""
  twitter: "https://twitter.com/rockerhx"

page_comment: false
logo: /images/avatar.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: rockerhx

baidu_tongji: f1811f144f64379f918cf1ef7bf3f3cb
favicon: /images/avatar-small.jpg

#mathjax
mathjax: true

# 'Read more' button
excerpt_link: 继续阅读

# Footer message
site_license: 本站点采用 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>
theme_message: 基于 <a href="http://hexo.io">Hexo</a> 搭建，使用 <a href="https://github.com/monniya/hexo-theme-new-vno ">new-vno</a> 主题，由<a href="https://monniya.com ">@Monniya</a> 修改自 <a href="https://github.com/lenbo-ma/hexo-theme-vno" target="_blank">Vno</a>, 原创出自<a href="http://github.com/onevcat/vno" target="_blank">onevcat</a>

